// Parcel Tracking Client
// Unified parcel tracking across carriers with status normalization, ETA prediction, and delivery event aggregation for multi-carrier logistics.
// Auto-generated by @ph-itdev/logistics-pipeline


const STATUSES = { CREATED: 0, PICKED_UP: 1, IN_TRANSIT: 2, OUT_FOR_DELIVERY: 3, DELIVERED: 4, EXCEPTION: -1 };

class ParcelTracker {
  constructor() { this.parcels = new Map(); this.events = []; }
  registerParcel(trackingNumber, { carrier = 'generic', origin, destination, weight }) {
    this.parcels.set(trackingNumber, { trackingNumber, carrier, origin, destination, weight, status: 'CREATED', statusLevel: 0, events: [], eta: null });
  }
  addEvent(trackingNumber, { status, location, details = '' }) {
    const p = this.parcels.get(trackingNumber);
    if (!p) throw new Error('Parcel not found');
    const level = STATUSES[status] ?? 2;
    const event = { status, location, details, timestamp: Date.now() };
    p.events.push(event);
    this.events.push({ trackingNumber, ...event });
    if (level > p.statusLevel || status === 'EXCEPTION') { p.status = status; p.statusLevel = level; }
  }
  setETA(trackingNumber, eta) { const p = this.parcels.get(trackingNumber); if (p) p.eta = eta; }
  getParcel(trackingNumber) { return this.parcels.get(trackingNumber) || null; }
  getByStatus(status) { return [...this.parcels.values()].filter(p => p.status === status); }
  getByCarrier(carrier) { return [...this.parcels.values()].filter(p => p.carrier === carrier); }
  getTransitTime(trackingNumber) {
    const p = this.parcels.get(trackingNumber);
    if (!p || p.events.length < 2) return null;
    return p.events[p.events.length - 1].timestamp - p.events[0].timestamp;
  }
  getAggregatedStats() {
    const parcels = [...this.parcels.values()];
    const byStatus = {};
    for (const p of parcels) byStatus[p.status] = (byStatus[p.status] || 0) + 1;
    const delivered = parcels.filter(p => p.statusLevel >= 4);
    const avgTransit = delivered.length ? delivered.reduce((s, p) => s + this.getTransitTime(p.trackingNumber), 0) / delivered.length : 0;
    return { total: parcels.length, byStatus, avgTransitTimeMs: Math.round(avgTransit) };
  }
}


module.exports = { ParcelTracker, STATUSES };
